export interface Tipster {
  slug: string;
  name: string;
  displayName: string;
  emoji: string;
  description: string;
  bio: string;
  specialty: string;
  color: string;
  pageTitle: string;
  metaDescription: string;
  puxadas: Record<string, string[]>;
  favoritos: string[];
}

export const TIPSTERS: Tipster[] = [
  {
    slug: 'puxada-do-mitao',
    name: 'Mitão',
    displayName: 'Puxada do Mitão',
    emoji: '🦁',
    description: 'As puxadas do Mitão são conhecidas pela força nos bichos grandes.',
    bio: 'Mitão é um dos palpiteiros mais respeitados do Brasil. Com anos de experiência no jogo do bicho, desenvolveu sua própria tabela de puxadas com foco nos bichos de maior porte e força.',
    specialty: 'Bichos grandes: Leão, Elefante, Touro e Urso',
    color: 'amber',
    pageTitle: 'Puxada do Mitão — Tabela de Puxadas do Jogo do Bicho',
    metaDescription: 'Confira a tabela de puxadas do Mitão no jogo do bicho. Palpites do Mitão com os melhores animais para apostar hoje. Veja o que o Mitão indica!',
    favoritos: ['leao', 'elefante', 'touro', 'urso'],
    puxadas: {
      avestruz:   ['Águia', 'Peru', 'Galo', 'Pavão'],
      aguia:      ['Avestruz', 'Galo', 'Peru', 'Pavão'],
      burro:      ['Cavalo', 'Touro', 'Elefante'],
      borboleta:  ['Gato', 'Leão', 'Tigre'],
      cachorro:   ['Gato', 'Macaco', 'Porco'],
      cabra:      ['Carneiro', 'Touro', 'Elefante', 'Urso'],
      carneiro:   ['Cabra', 'Vaca', 'Touro'],
      camelo:     ['Elefante', 'Urso', 'Burro'],
      cobra:      ['Jacaré', 'Porco', 'Gato'],
      coelho:     ['Carneiro', 'Burro', 'Veado'],
      cavalo:     ['Burro', 'Touro', 'Vaca'],
      elefante:   ['Urso', 'Leão', 'Tigre', 'Cabra'],
      galo:       ['Avestruz', 'Águia', 'Pavão', 'Peru'],
      gato:       ['Leão', 'Tigre', 'Cobra'],
      jacare:     ['Cobra', 'Porco', 'Macaco'],
      leao:       ['Elefante', 'Tigre', 'Urso', 'Gato'],
      macaco:     ['Cachorro', 'Jacaré', 'Peru'],
      porco:      ['Cobra', 'Jacaré', 'Cachorro'],
      pavao:      ['Avestruz', 'Galo', 'Peru', 'Águia'],
      peru:       ['Galo', 'Pavão', 'Avestruz', 'Veado'],
      touro:      ['Vaca', 'Burro', 'Elefante', 'Carneiro'],
      tigre:      ['Leão', 'Gato', 'Elefante'],
      urso:       ['Leão', 'Elefante', 'Camelo'],
      veado:      ['Coelho', 'Peru', 'Cabra'],
      vaca:       ['Touro', 'Carneiro', 'Avestruz'],
    },
  },
  {
    slug: 'puxadas-do-fabio',
    name: 'Fábio',
    displayName: 'Puxadas do Fábio',
    emoji: '🎯',
    description: 'Fábio é especialista em bichos de meia tabela com alta frequência.',
    bio: 'Fábio acompanha o jogo do bicho há mais de duas décadas. Sua metodologia é baseada em frequência de saídas e correlação entre grupos do meio da tabela, especialmente os grupos 09 a 17.',
    specialty: 'Meia tabela: Cobra, Coelho, Cavalo, Elefante e Galo',
    color: 'blue',
    pageTitle: 'Puxadas do Fábio — Tabela de Puxadas do Jogo do Bicho',
    metaDescription: 'Veja as puxadas do Fábio para o jogo do bicho hoje. Tabela completa com as indicações do Fábio para todos os 25 animais. Palpites confiáveis!',
    favoritos: ['cobra', 'cavalo', 'elefante', 'galo'],
    puxadas: {
      avestruz:   ['Pavão', 'Peru', 'Galo'],
      aguia:      ['Coelho', 'Galo', 'Avestruz'],
      burro:      ['Coelho', 'Cobra', 'Cavalo'],
      borboleta:  ['Cachorro', 'Gato', 'Cabra'],
      cachorro:   ['Gato', 'Camelo', 'Cobra'],
      cabra:      ['Carneiro', 'Cobra', 'Elefante'],
      carneiro:   ['Cabra', 'Coelho', 'Vaca'],
      camelo:     ['Cachorro', 'Cobra', 'Macaco'],
      cobra:      ['Jacaré', 'Gato', 'Coelho', 'Porco'],
      coelho:     ['Águia', 'Cobra', 'Cavalo', 'Burro'],
      cavalo:     ['Cobra', 'Burro', 'Elefante', 'Coelho'],
      elefante:   ['Cavalo', 'Cobra', 'Galo', 'Leão'],
      galo:       ['Elefante', 'Águia', 'Cobra', 'Pavão'],
      gato:       ['Cobra', 'Cachorro', 'Leão'],
      jacare:     ['Cobra', 'Porco', 'Macaco', 'Borboleta'],
      leao:       ['Gato', 'Elefante', 'Tigre'],
      macaco:     ['Jacaré', 'Cachorro', 'Cobra'],
      porco:      ['Cobra', 'Jacaré', 'Peru'],
      pavao:      ['Galo', 'Avestruz', 'Peru'],
      peru:       ['Pavão', 'Galo', 'Porco', 'Veado'],
      touro:      ['Vaca', 'Cavalo', 'Burro'],
      tigre:      ['Leão', 'Cobra', 'Gato'],
      urso:       ['Camelo', 'Elefante', 'Leão'],
      veado:      ['Peru', 'Coelho', 'Cabra'],
      vaca:       ['Touro', 'Avestruz', 'Coelho'],
    },
  },
  {
    slug: 'palpite-do-tavinho',
    name: 'Tavinho',
    displayName: 'Palpite do Tavinho',
    emoji: '🔮',
    description: 'Tavinho combina intuição e estatística nos seus palpites diários.',
    bio: 'Tavinho é conhecido por misturar análise estatística com intuição. Seus palpites têm foco nas dezenas da sorte e nos padrões de saída noturna, especialmente no PTN e Federal.',
    specialty: 'Foco noturno: PTN e Federal — Porco, Pavão, Peru, Touro',
    color: 'purple',
    pageTitle: 'Palpite do Tavinho — Tabela de Puxadas do Jogo do Bicho',
    metaDescription: 'Descubra os palpites do Tavinho para o jogo do bicho. Tabela de puxadas do Tavinho com os melhores animais e dezenas para apostar hoje!',
    favoritos: ['porco', 'pavao', 'peru', 'touro'],
    puxadas: {
      avestruz:   ['Galo', 'Águia', 'Pavão'],
      aguia:      ['Pavão', 'Peru', 'Avestruz'],
      burro:      ['Cabra', 'Cavalo', 'Carneiro'],
      borboleta:  ['Leão', 'Gato', 'Elefante'],
      cachorro:   ['Porco', 'Macaco', 'Gato'],
      cabra:      ['Tigre', 'Urso', 'Elefante'],
      carneiro:   ['Cabra', 'Coelho', 'Burro'],
      camelo:     ['Urso', 'Macaco', 'Elefante'],
      cobra:      ['Porco', 'Jacaré', 'Gato'],
      coelho:     ['Burro', 'Veado', 'Carneiro'],
      cavalo:     ['Touro', 'Burro', 'Cabra'],
      elefante:   ['Tigre', 'Cabra', 'Urso'],
      galo:       ['Pavão', 'Peru', 'Avestruz'],
      gato:       ['Cachorro', 'Cobra', 'Tigre'],
      jacare:     ['Cobra', 'Borboleta', 'Porco'],
      leao:       ['Urso', 'Tigre', 'Elefante'],
      macaco:     ['Peru', 'Cachorro', 'Jacaré'],
      porco:      ['Peru', 'Jacaré', 'Cobra', 'Cachorro'],
      pavao:      ['Galo', 'Peru', 'Águia', 'Avestruz'],
      peru:       ['Pavão', 'Porco', 'Galo', 'Macaco'],
      touro:      ['Cavalo', 'Vaca', 'Carneiro'],
      tigre:      ['Cabra', 'Elefante', 'Leão'],
      urso:       ['Cabra', 'Camelo', 'Leão'],
      veado:      ['Coelho', 'Cabra', 'Burro'],
      vaca:       ['Carneiro', 'Touro', 'Avestruz'],
    },
  },
  {
    slug: 'puxada-do-tavinho',
    name: 'Tavinho',
    displayName: 'Puxada do Tavinho',
    emoji: '⚡',
    description: 'A tabela de puxadas do Tavinho com foco em correntes de bichos.',
    bio: 'Diferente dos seus palpites pontuais, a Puxada do Tavinho é a tabela de correntes — sequências de animais que historicamente saem juntos na mesma semana.',
    specialty: 'Correntes semanais: sequências de 3 a 4 bichos',
    color: 'emerald',
    pageTitle: 'Puxada do Tavinho — Sequências e Correntes do Jogo do Bicho',
    metaDescription: 'A puxada do Tavinho com as melhores sequências e correntes do jogo do bicho. Tabela atualizada com os animais que o Tavinho indica para hoje!',
    favoritos: ['galo', 'cobra', 'cachorro', 'vaca'],
    puxadas: {
      avestruz:   ['Vaca', 'Galo', 'Pavão', 'Peru'],
      aguia:      ['Galo', 'Pavão', 'Avestruz'],
      burro:      ['Cobra', 'Cavalo', 'Elefante'],
      borboleta:  ['Cabra', 'Gato', 'Cachorro'],
      cachorro:   ['Cobra', 'Gato', 'Galo', 'Pavão'],
      cabra:      ['Elefante', 'Urso', 'Tigre'],
      carneiro:   ['Vaca', 'Coelho', 'Cabra'],
      camelo:     ['Elefante', 'Macaco', 'Urso'],
      cobra:      ['Cachorro', 'Jacaré', 'Gato', 'Porco'],
      coelho:     ['Carneiro', 'Vaca', 'Águia'],
      cavalo:     ['Burro', 'Elefante', 'Touro'],
      elefante:   ['Leão', 'Urso', 'Cabra'],
      galo:       ['Cachorro', 'Avestruz', 'Pavão', 'Peru'],
      gato:       ['Cachorro', 'Cobra', 'Leão'],
      jacare:     ['Cobra', 'Macaco', 'Porco'],
      leao:       ['Elefante', 'Gato', 'Urso'],
      macaco:     ['Jacaré', 'Peru', 'Cabra'],
      porco:      ['Jacaré', 'Cobra', 'Peru'],
      pavao:      ['Galo', 'Avestruz', 'Águia'],
      peru:       ['Veado', 'Galo', 'Pavão', 'Porco'],
      touro:      ['Cavalo', 'Vaca', 'Burro'],
      tigre:      ['Leão', 'Cabra', 'Gato'],
      urso:       ['Leão', 'Elefante', 'Camelo'],
      veado:      ['Peru', 'Burro', 'Carneiro'],
      vaca:       ['Avestruz', 'Touro', 'Carneiro'],
    },
  },
  {
    slug: 'puxada-da-jacinta',
    name: 'Jacinta',
    displayName: 'Puxada da Jacinta',
    emoji: '🌺',
    description: 'Jacinta é referência nos bichos miúdos e nas puxadas da tarde.',
    bio: 'Jacinta é uma das palpiteiras mais queridas do interior. Seus métodos vêm de décadas de observação nas extrações da tarde (PT e PTM). É especialista nos bichos miúdos: Borboleta, Coelho, Gato e Veado.',
    specialty: 'Bichos miúdos e tarde: Borboleta, Coelho, Gato, Veado',
    color: 'rose',
    pageTitle: 'Puxada da Jacinta — Tabela de Puxadas do Jogo do Bicho',
    metaDescription: 'Confira a puxada da Jacinta no jogo do bicho. Tabela completa com as indicações da Jacinta para todos os animais. A favorita das extrações da tarde!',
    favoritos: ['borboleta', 'coelho', 'gato', 'veado'],
    puxadas: {
      avestruz:   ['Pavão', 'Galo', 'Águia'],
      aguia:      ['Coelho', 'Avestruz', 'Pavão'],
      burro:      ['Coelho', 'Veado', 'Carneiro'],
      borboleta:  ['Gato', 'Coelho', 'Veado', 'Cachorro'],
      cachorro:   ['Gato', 'Borboleta', 'Pavão'],
      cabra:      ['Carneiro', 'Veado', 'Coelho'],
      carneiro:   ['Coelho', 'Vaca', 'Cabra'],
      camelo:     ['Burro', 'Coelho', 'Macaco'],
      cobra:      ['Gato', 'Jacaré', 'Burro'],
      coelho:     ['Borboleta', 'Veado', 'Carneiro', 'Águia'],
      cavalo:     ['Veado', 'Burro', 'Coelho'],
      elefante:   ['Cabra', 'Leão', 'Tigre'],
      galo:       ['Pavão', 'Avestruz', 'Peru'],
      gato:       ['Borboleta', 'Coelho', 'Cachorro', 'Cobra'],
      jacare:     ['Cobra', 'Borboleta', 'Macaco'],
      leao:       ['Tigre', 'Gato', 'Elefante'],
      macaco:     ['Cachorro', 'Jacaré', 'Camelo'],
      porco:      ['Cobra', 'Jacaré', 'Cachorro'],
      pavao:      ['Galo', 'Águia', 'Avestruz', 'Coelho'],
      peru:       ['Veado', 'Galo', 'Pavão'],
      touro:      ['Vaca', 'Carneiro', 'Burro'],
      tigre:      ['Leão', 'Gato', 'Elefante'],
      urso:       ['Elefante', 'Leão', 'Cabra'],
      veado:      ['Coelho', 'Borboleta', 'Cabra', 'Peru'],
      vaca:       ['Carneiro', 'Coelho', 'Touro'],
    },
  },
];
